Первая часть. Задания 1-7
arrayxx/traineeKotlin pull request #3
Opened 2023-11-22 20:37 UTC by arrayxx

2023-11-29 12:35 UTC, vrnvorona requested changes
в файлах нет main функций. код должен быть таким чтобы его можно было скопировать и он работал. сейчас это как будто скетч и надо оборачивать в main.

также не хватает конечно комментов внутри файлов с описанием задания 😢

2023-11-29 12:35 UTC, vrnvorona commented on src/main/object-oriented-programming/Cars.kts
> +myCar.let {
логичнее было бы использовать run или apply чтобы не писать it. а просто писать color = и year =

2023-11-29 12:35 UTC, vrnvorona commented on src/main/object-oriented-programming/DayOfWeek.kts
> +    fun listOfDays(days: DayOfWeek): String {
days лишний параметр

2023-11-29 12:35 UTC, vrnvorona commented on src/main/object-oriented-programming/Person.main.kts
> +    companion object {
попробуй так:

1. сделай поля изменяемыми
2. создай два Person
3. Измени второму любой параметр
4. посмотри какое значение у первого Person

2023-11-29 12:35 UTC, vrnvorona commented on src/main/object-oriented-programming/Person.main.kts
> +        private val name = "Савелий"
эти поля должны браться из конструктора

2023-11-29 12:35 UTC, vrnvorona commented on src/main/object-oriented-programming/PersonGetSet.main.kts
после Person.main (кстати зачем приписка main у всех файлов?) поправь и это задание

2023-11-29 12:35 UTC, vrnvorona commented on src/main/object-oriented-programming/PersonGetSet.main.kts
> +                    println("Строка слишком длинная! Длина должна быть 50 символов")
введи имя длиннее 50 символов и проверь значение

2023-11-29 12:35 UTC, vrnvorona commented on src/main/object-oriented-programming/PersonGetSet.main.kts
> +                    println("Ошибка! Возраст не может быть отрицательным")
тут аналогично как с именем, введи отрицательное и проверь что получится

2023-11-29 12:35 UTC, vrnvorona commented on src/main/object-oriented-programming/MathUtils.main.kts
> +    fun add(a: Int, b: Int) =  println("Overload fun add takes 2 arguments: $a, $b")
задание выполнено, но можно было все таки сделать операцию сложения 😢

2023-11-29 12:40 UTC, arrayxx commented
> в файлах нет main функций. код должен быть таким чтобы его можно было скопировать и он работал. сейчас это как будто скетч и надо оборачивать в main.
> 
> также не хватает конечно комментов внутри файлов с описанием задания 😢

А так это Kotlin script, там чтобы корректно работало на форумах посоветовали добавить приписку `main` после названия файла, без этого синтаксис не подсвечивался. Я ес честно хз, насколько так можно делать  

А так я засунул в скрипт, чтоб не писать main каждый раз

2023-11-29 12:59 UTC, vrnvorona commented
> > в файлах нет main функций. код должен быть таким чтобы его можно было скопировать и он работал. сейчас это как будто скетч и надо оборачивать в main.
> > также не хватает конечно комментов внутри файлов с описанием задания 😢
> 
> А так это Kotlin script, там чтобы корректно работало на форумах посоветовали добавить приписку `main` после названия файла, без этого синтаксис не подсвечивался. Я ес честно хз, насколько так можно делать
> 
> А так я засунул в скрипт, чтоб не писать main каждый раз

я не знаю как в IDEA делать скрипты или что то такое, было бы удобнее если бы через .kt все делалось 🦀

2023-11-30 10:08 UTC, vrnvorona commented on src/main/object-oriented-programming/PersonGetSet.main.kts
> +                    println("Строка слишком длинная! Длина должна быть 50 символов")
нужен ли if else или можно обработать ошибку одним if?

2023-12-04 14:18 UTC, vrnvorona commented on src/main/object-oriented-programming/PersonGetSet.main.kts
> +                    println("Строка слишком длинная! Длина должна быть 50 символов")
еще актуально

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/PersonGetSet.main.kts
> +                if (value.length >= 50) {
фикс почти правильный но было <= 50 стало >= 50 -> граничные значения поменялись, теперь 50 нельзя а 49 можно

ну и сообщение "должна быть 50 а 50 нельзя = конфуз". "не больше 50" правильнее

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/Dependency Injection.kt
> +        tires = object: Tires() {
весь смысл DI разрашил тем что ты внутри класса который зависит определил изменения в зависимости. если уж так хотел поменять сделал бы это при вызове в main и передал бы измененный Tires а не вот так

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/Dependency Injection.kt
> +        tires = object: Tires() {
еще намек на то что неверно - необходимость использовать var

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/Flyable.kt
> +fun birdFly() {
можно было не делать функцию ради создания объекта а просто вызывать их в main но это мелочи

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/Mammal.kt
> +    open fun fly(): String { return "can't fly" }
так класс то не млекопетающее... но трюк с объектом прикольный

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/MathOperation.kt
> +            null
не уверен что null нужен явным образом, проверял?

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/MathOperation.kt
> +математические операции (например, Add, Subtract, Multiply, Divide). Создайте функцию,
не совсем по заданию сделал, надо было общую функцию сделать и она просто операцию бы делала, а наследники MathOperation должны были оверрайдить функцию

не крит т.к. с sealed частью справился но внимательнее бы

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/Repository.kt
> +    init {
как то ты инвертировал. User должен быть просто положен в репозиторий. а у тебя внутри юзера иницилизируется несколько репозиториев с разными типами

так же конкретно UserRepository мог не быть типизированным а передать User в Repository но это мелочь т.к. если есть подклассы у юзера то пришлось бы делать ковариантный дженерик и сразу стало х100 сложно

2024-01-09 17:48 UTC, vrnvorona commented on src/main/object-oriented-programming/Shape.kt
> +    class Circle(private val pi: Double = PI, private val r: Double): Shape() {
передаешь PI на случай разных констант для разных вселенных? :)

2024-01-15 14:58 UTC, vrnvorona commented on src/main/object-oriented-programming/Dependency Injection.kt
> +// создадим класс Шины, который принимает на вход тип резины
оч конечно сложно сделал по итогу
нужно было просто сделать интерфейс Tires и два класса Summer/WinterTires и передавать в Car либо Summer либо Winter

2024-01-15 15:00 UTC, vrnvorona commented on src/main/object-oriented-programming/MathOperation.kt
> +                throw ArithmeticException("Деление на ноль!")
в прошлой версии ты хэндлил ошибку деления на ноль, а сейчас просто кидаешь ошибку, можно тогда было не делать обработку и сразу вернуть a/b т.к. оно тоже кинет ошибку)

2024-01-15 15:01 UTC, vrnvorona commented on src/main/object-oriented-programming/Mammal.kt
> +    open fun fly(): String { return "can't fly" }
имел в виду что CanFly не обязательно млекопитающее поэтому странно делать вначале can't fly

2024-01-23 20:19 UTC, vrnvorona approved these changes

2024-01-24 18:15 UTC, merged